# Generated by Django 3.1.4 on 2020-12-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('sum_insured', models.FloatField()),
                ('dob', models.DateField()),
                ('policy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients_information.policy_type')),
            ],
        ),
    ]
